version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10.
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: stellar/transfer-server-validator
    docker:
      - image: circleci/node:latest
jobs:
  publish-build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME:latest .
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  publish-build-deploy:
    jobs:
      - publish-build:
          filters:
            branches:
              only: master
      - heroku/deploy-via-git:
          requires:
            - publish-build
          filters:
            branches:
              only: master