version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: stellar/transfer-server-validator
    docker:
      - image: circleci/node:latest
jobs:
  publish-build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME:latest .
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  deploy:
    executor: docker-publisher
    steps:
      - checkout
      - run: 
          command: |
            git remote add heroku https://git.heroku.com/anchor-validator.git || true
            git push heroku master
workflows:
  version: 2
  publish-build:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master